"use client";

import Link from "next/link";
import { Bot, ChevronLeft, MessageCircleMore, Send, X } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";

type Answer = {
  question: string;
  answer: string;
  keywords: string[];
  link?: { href: string; label: string };
};

const answers: Answer[] = [
  { question: "Qu'est-ce que l'hydroseeding ?", answer: "C'est une projection hydraulique qui associe de l'eau, des semences et des fibres de paillage. Le mélange est choisi en fonction du terrain et de l'objectif du projet.", keywords: ["hydroseeding", "hydroseed", "hydrosemis", "technique", "definition"], link: { href: "/hydroseeding", label: "Découvrir l'hydroseeding" } },
  { question: "Qu'est-ce que l'hydromulching ?", answer: "L'hydromulching projette une couverture de fibres de paillage et de liant sur le sol. Elle aide à conserver l'humidité de surface et à limiter l'érosion superficielle. Des semences peuvent être ajoutées selon le projet.", keywords: ["hydromulching", "hydromulch", "paillage", "fibre"], link: { href: "/hydromulching", label: "Découvrir l'hydromulching" } },
  { question: "Quelle différence entre hydroseeding et hydromulching ?", answer: "L'hydroseeding vise principalement l'installation d'une végétation à partir de semences. L'hydromulching met l'accent sur la couverture et la protection du sol ; il peut être associé à des semences selon le besoin.", keywords: ["difference", "différence", "hydroseeding hydromulching", "choisir"], link: { href: "/hydromulching", label: "Comparer les deux approches" } },
  { question: "Quels terrains peuvent être traités ?", answer: "Talus, zones de chantier, grandes surfaces, espaces paysagers et sols nus à protéger peuvent être concernés. Nous regardons d'abord le sol, la pente, l'accès et le résultat recherché.", keywords: ["terrain", "surface", "talus", "pente", "chantier", "adapté", "application"], link: { href: "/applications", label: "Voir les applications" } },
  { question: "Faut-il préparer le terrain ?", answer: "Pas systématiquement. Nous évaluons le terrain et proposons seulement les interventions utiles. Une surface compacte, instable ou encombrée peut toutefois nécessiter une préparation avant la projection.", keywords: ["preparer", "préparer", "préparation", "sol", "compact", "nivellement" ] },
  { question: "Peut-on intervenir sur une pente ?", answer: "Oui, la pente fait partie des éléments étudiés. L'exposition au ruissellement, la stabilité du sol et l'accès permettent de définir si une projection seule suffit ou si une protection complémentaire est nécessaire.", keywords: ["pente", "talus", "incliné", "erosion", "érosion", "ruissellement"] },
  { question: "Comment choisissez-vous les semences ?", answer: "Le mélange n'est pas identique pour tous les projets. Il est choisi selon le sol, le climat local, l'exposition, l'usage du terrain et l'objectif de végétalisation.", keywords: ["semence", "graine", "mélange", "melange", "choisir", "espèce", "espece"] },
  { question: "Pourquoi arroser après un hydroseeding ?", answer: "Les premières semaines, l'eau aide à conserver un environnement favorable à la germination. Le paillage doit rester humide au toucher, sans être détrempé ni créer de ruissellement.", keywords: ["arroser", "arrosage", "irrigation", "eau", "humide", "apres", "après"], link: { href: "/guide-irrigation", label: "Voir le guide 30 jours" } },
  { question: "Combien de fois arroser les premiers jours ?", answer: "En repère général, comptez 2 à 4 passages courts par jour pendant les jours 1 à 7. La météo, le vent, la pente, le débit et le sol imposent d'ajuster : observez toujours l'humidité du paillage.", keywords: ["combien", "fois", "jour", "jours", "premier", "fréquence", "frequence", "2", "4"], link: { href: "/guide-irrigation", label: "Voir le calendrier complet" } },
  { question: "Combien de temps faut-il arroser ?", answer: "Il n'existe pas une durée identique pour tous les terrains. Sur un sol lourd, 5 à 15 minutes par zone peuvent parfois suffire ; vérifiez surtout que le paillage est humide sans flaques ni écoulement.", keywords: ["minute", "minutes", "temps", "duree", "durée", "longtemps"] },
  { question: "Que faire s'il fait très chaud ou s'il y a du vent ?", answer: "Contrôlez davantage le paillage. S'il sèche vite, ajoutez un passage court et doux plutôt que d'arroser fortement en une seule fois.", keywords: ["chaud", "chaleur", "canicule", "vent", "sec", "secher", "sécher"] },
  { question: "Dois-je arroser quand il pleut ?", answer: "Vérifiez d'abord le terrain. Une pluie légère ne remplace pas toujours l'irrigation ; si le paillage reste humide, il n'est pas nécessaire d'ajouter de l'eau immédiatement.", keywords: ["pluie", "pleut", "pluvieux", "orage"] },
  { question: "Quand les premières pousses apparaissent-elles ?", answer: "Le délai dépend des semences, de la température, de l'humidité et du terrain. Le plus important est de maintenir des conditions d'humidité régulières pendant la période de germination.", keywords: ["pousse", "germination", "germer", "délai", "delai", "quand", "apparaitre", "apparaître"] },
  { question: "Pourquoi certaines zones poussent moins bien ?", answer: "Les écarts peuvent venir de la météo, de l'ombre, de la pente, de l'humidité, de la nature du sol ou d'un ruissellement localisé. Une observation du terrain permet d'identifier la bonne action.", keywords: ["zone", "moins", "trou", "clairsemé", "clairseme", "inégal", "inegal", "pousse pas"] },
  { question: "Que faire si l'eau ruisselle ?", answer: "Réduisez l'intensité du jet ou divisez l'arrosage en passages plus courts. L'objectif est d'humidifier le paillage sans déplacer le mélange ni former de flaques.", keywords: ["ruissellement", "flaque", "flaques", "coule", "ecoulement", "écoulement"] },
  { question: "Quand tondre un nouveau gazon ?", answer: "Attendez que le gazon soit suffisamment implanté et que le sol soit stable. Le bon moment dépend de l'état réel du terrain ; demandez conseil avant une première tonte si vous avez un doute.", keywords: ["tondre", "tonte", "couper", "gazon"] },
  { question: "Est-ce que cela protège contre l'érosion ?", answer: "Une couverture de paillage peut limiter l'érosion superficielle pendant l'installation de la végétation. Sur un sol instable ou une pente très exposée, une étude plus complète peut être nécessaire.", keywords: ["erosion", "érosion", "protéger", "protection", "stabiliser", "stabilité"] },
  { question: "À quelle saison intervenir ?", answer: "La période dépend du projet, des espèces choisies et des conditions météo. Nous regardons ces éléments avec vous pour choisir une intervention cohérente, plutôt que promettre une date identique pour tous les terrains.", keywords: ["saison", "printemps", "été", "ete", "automne", "hiver", "periode", "période"] },
  { question: "Est-ce adapté aux grandes surfaces ?", answer: "Oui, l'application hydraulique peut être intéressante sur de grandes surfaces. L'accès, la topographie et le résultat attendu sont étudiés avant de définir la solution.", keywords: ["grande", "grandes", "surface", "hectare", "m2", "m²"] },
  { question: "Peut-on hydrosemer un petit jardin ?", answer: "Oui, selon la configuration et l'objectif. La surface seule ne suffit pas à décider : l'accès, l'état du sol et le résultat recherché sont aussi importants.", keywords: ["petit", "jardin", "particulier", "maison", "pelouse"] },
  { question: "Peut-on intervenir dans un espace public ?", answer: "Oui, les espaces publics, accotements et zones paysagères peuvent être étudiés. Les contraintes d'accès, de fréquentation et de sécurité doivent être intégrées au projet.", keywords: ["public", "collectivite", "collectivité", "commune", "mairie", "voirie", "accotement"] },
  { question: "L'accès au terrain est-il important ?", answer: "Oui. L'accès influence l'organisation du chantier, le positionnement du matériel et la manière d'atteindre la zone à traiter. Des photos et les dimensions des accès nous aident à préparer l'intervention.", keywords: ["acces", "accès", "portail", "passage", "difficile", "machine", "matériel"] },
  { question: "Que faut-il retirer avant l'intervention ?", answer: "Les déchets, pierres mobiles, objets et végétaux indésirables peuvent devoir être retirés. Nous vous indiquons ce qui est réellement nécessaire après avoir regardé le terrain.", keywords: ["retirer", "nettoyer", "pierre", "dechet", "déchet", "mauvaise herbe", "désherber"] },
  { question: "Peut-on projeter sur une pelouse existante ?", answer: "Cela dépend de l'état de la pelouse et de l'objectif. Une végétation dense peut empêcher les semences d'atteindre correctement le sol ; une préparation peut donc être utile.", keywords: ["pelouse existante", "ancien gazon", "regarnir", "gazon actuel", "déjà", "deja"] },
  { question: "Est-ce adapté à un sol argileux ?", answer: "Un sol argileux peut être concerné, mais sa compaction, son drainage et sa capacité à retenir l'eau doivent être observés. Le mélange et la préparation éventuelle sont ajustés en conséquence.", keywords: ["argile", "argileux", "lourd", "collant", "sol lourd"] },
  { question: "Est-ce adapté à un sol sableux ?", answer: "Un sol sableux sèche généralement plus vite et retient moins l'eau. Le choix du mélange et le suivi d'arrosage doivent donc être adaptés à ce comportement.", keywords: ["sable", "sableux", "drainant", "sec"] },
  { question: "Et si le terrain est très caillouteux ?", answer: "Un terrain très caillouteux doit être observé avant de choisir la méthode. Les pierres, le manque de terre fine et la stabilité de la surface peuvent nécessiter une préparation complémentaire.", keywords: ["caillou", "caillouteux", "pierre", "roche", "rocheux"] },
  { question: "Faut-il analyser le sol ?", answer: "Une observation du sol est toujours utile. Selon le projet, une analyse plus poussée peut aider à comprendre le pH, la fertilité ou certaines contraintes avant de choisir les composants.", keywords: ["analyse", "ph", "fertilite", "fertilité", "terre", "tester"] },
  { question: "Le drainage du terrain est-il important ?", answer: "Oui. Une eau qui stagne ou ruisselle fortement peut perturber l'installation de la végétation. Le drainage et les écoulements doivent être pris en compte avant l'intervention.", keywords: ["drainage", "drainer", "stagne", "eau stagnante", "boue", "inondé"] },
  { question: "Faut-il un système d'arrosage automatique ?", answer: "Ce n'est pas toujours obligatoire, mais il facilite un arrosage régulier, surtout sur une grande surface. L'essentiel est de pouvoir humidifier toute la zone de façon douce et homogène.", keywords: ["automatique", "arroseur", "programmateur", "systeme", "système", "irrigation automatique"] },
  { question: "Que faire si je n'ai pas d'arrivée d'eau ?", answer: "Il faut anticiper une solution avant l'intervention. Les premiers jours demandent une humidité régulière ; sans moyen d'arrosage adapté, la réussite peut être fortement compromise.", keywords: ["pas eau", "sans eau", "arrivee", "arrivée", "robinet", "citerne"] },
  { question: "Puis-je marcher sur la zone après l'intervention ?", answer: "Il vaut mieux limiter les passages pendant la germination. Le piétinement peut marquer le sol, déplacer le paillage et fragiliser les jeunes pousses.", keywords: ["marcher", "passer", "piétiner", "pietiner", "circuler", "passage"] },
  { question: "Les enfants ou animaux peuvent-ils aller sur la zone ?", answer: "Il est préférable de protéger temporairement la zone du passage. Demandez-nous aussi les consignes adaptées aux composants utilisés sur votre chantier.", keywords: ["chien", "chat", "animal", "animaux", "enfant", "enfants", "sécurité", "securite"] },
  { question: "Pourquoi le mélange projeté est-il coloré ?", answer: "Une coloration peut servir de repère visuel pendant l'application afin de mieux contrôler la couverture de la surface. Son aspect évolue ensuite avec le séchage et la météo.", keywords: ["vert", "bleu", "couleur", "coloré", "colore", "teinte"] },
  { question: "Le paillage va-t-il disparaître ?", answer: "Les fibres évoluent progressivement avec l'humidité, la météo et l'installation de la végétation. Leur aspect visible diminue au fil du temps.", keywords: ["paillage", "disparaitre", "disparaître", "fibre", "reste", "partir"] },
  { question: "Que faire après un gros orage ?", answer: "Observez la zone sans la piétiner : cherchez d'éventuels écoulements, déplacements de paillage ou zones dénudées. Envoyez-nous des photos si quelque chose vous semble anormal.", keywords: ["orage", "tempete", "tempête", "forte pluie", "dégât", "degat"] },
  { question: "Le gel peut-il gêner la germination ?", answer: "Oui, les températures basses peuvent ralentir ou interrompre temporairement la germination. La période d'intervention doit tenir compte des semences et des conditions locales.", keywords: ["gel", "geler", "froid", "gelée", "gelee", "hiver"] },
  { question: "L'ombre change-t-elle le résultat ?", answer: "Oui. Une zone ombragée reçoit moins de lumière et conserve parfois l'humidité différemment. Le choix des semences et le rythme d'arrosage doivent en tenir compte.", keywords: ["ombre", "ombragé", "ombrage", "soleil", "lumiere", "lumière"] },
  { question: "Les mauvaises herbes peuvent-elles apparaître ?", answer: "Oui, des graines déjà présentes dans le sol peuvent germer en même temps. La réaction adaptée dépend de leur quantité, de leur espèce et de l'état des jeunes pousses.", keywords: ["mauvaise herbe", "adventice", "herbe indésirable", "indesirable", "désherber"] },
  { question: "Faut-il ajouter de l'engrais après la projection ?", answer: "N'ajoutez rien automatiquement. Le mélange initial et les besoins du terrain doivent être pris en compte ; demandez conseil avant tout apport complémentaire.", keywords: ["engrais", "fertilisant", "fertiliser", "amendement", "nourrir"] },
  { question: "Que faire après les 30 premiers jours ?", answer: "Lorsque la végétation est installée, les arrosages deviennent généralement plus espacés et plus profonds. La tonte, la fertilisation et l'entretien dépendent ensuite du mélange et de l'usage du terrain.", keywords: ["apres 30", "après 30", "un mois", "entretien", "ensuite", "suite"] },
  { question: "Que faire si une zone reste clairsemée ?", answer: "Ne corrigez pas trop vite. Comparez l'humidité, l'exposition et le sol avec le reste du terrain, puis envoyez-nous des photos pour déterminer s'il faut attendre ou intervenir.", keywords: ["clairsemé", "clairseme", "trou", "vide", "reprendre", "ressemer"] },
  { question: "Le résultat est-il garanti ?", answer: "La germination dépend aussi de l'arrosage, de la météo, du sol et du suivi après l'intervention. Nous préférons expliquer clairement ces facteurs et vous accompagner plutôt que promettre un résultat indépendant des conditions.", keywords: ["garantie", "garantir", "assuré", "assure", "réussite", "reussite"] },
  { question: "Combien de temps dure une intervention ?", answer: "La durée dépend de la surface, de l'accès, de la pente et des préparations nécessaires. Nous pouvons donner un repère après avoir compris le terrain.", keywords: ["durée chantier", "duree chantier", "temps intervention", "combien temps", "journée", "journee"] },
  { question: "Quelles photos envoyer pour étudier le projet ?", answer: "Envoyez une vue générale, plusieurs angles du terrain, les pentes, les accès et les zones présentant une difficulté particulière. Une photo prise avec du recul est souvent très utile.", keywords: ["photo", "photos", "image", "envoyer", "angle", "vue"] },
  { question: "Comment savoir quelle solution choisir ?", answer: "Vous n'avez pas besoin de choisir seul. Décrivez le terrain et votre objectif ; nous vous expliquons si l'hydroseeding, l'hydromulching ou une autre préparation paraît la plus cohérente.", keywords: ["quelle solution", "choisir", "conseil", "besoin", "méthode", "methode"] },
  { question: "Est-ce que vos équipes réalisent les chantiers ?", answer: "Oui. Hydrovert Solutions réalise directement ses interventions. Vous échangez avec une équipe impliquée dans votre projet, sans multiplication d'intermédiaires.", keywords: ["équipe", "equipe", "sous traitance", "sous-traitance", "intermediaire", "intermédiaire", "realisez", "réalisez"] },
  { question: "Quel accompagnement proposez-vous ?", answer: "Nous échangeons avant l'intervention pour comprendre le terrain et l'objectif, puis restons disponibles pour les conseils utiles après la projection, notamment sur l'arrosage.", keywords: ["accompagnement", "suivi", "conseil", "apres", "après", "disponible"] },
  { question: "Comment demander un devis ?", answer: "Indiquez la localisation, la surface approximative, la pente ou les contraintes, votre objectif et, si possible, quelques photos. Ces éléments permettent de démarrer un échange utile.", keywords: ["devis", "demande", "projet", "contacter"], link: { href: "/devis", label: "Préparer une demande" } },
  { question: "Intervenez-vous partout en France ?", answer: "Le site présente Hydrovert Solutions comme intervenant en France. Pour confirmer la faisabilité et les conditions de votre zone, transmettez-nous la localisation de votre terrain.", keywords: ["france", "ville", "departement", "département", "zone", "distance", "intervenir"] },
];

const popular = [answers[0], answers[7], answers[2], answers.find((item) => item.question === "Comment demander un devis ?")!];

function normalize(value: string) {
  return value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");
}

export default function FaqBubble() {
  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState<Answer | null>(null);

  const results = useMemo(() => {
    const words = normalize(query).split(/\s+/).filter((word) => word.length > 2);
    if (!words.length) return popular;
    return answers.map((item) => ({ item, score: item.keywords.filter((keyword) => words.some((word) => normalize(keyword).includes(word) || word.includes(normalize(keyword)))).length })).filter(({ score }) => score > 0).sort((a, b) => b.score - a.score).slice(0, 4).map(({ item }) => item);
  }, [query]);

  function choose(answer: Answer) { setSelected(answer); setQuery(""); }
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (results[0]) choose(results[0]); }

  return <div className="fixed bottom-4 right-4 z-[60] sm:bottom-6 sm:right-6">
    {open && <section aria-label="Assistant Hydrovert" className="mb-3 w-[calc(100vw-2rem)] max-w-sm overflow-hidden rounded-3xl border border-[#dbe5d4] bg-[#f7f8f4] shadow-2xl shadow-black/20">
      <header className="flex items-center justify-between bg-[#10271d] px-5 py-4 text-white"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-full bg-[#c0ea93] text-[#10271d]"><Bot size={20}/></span><span><strong className="block text-sm">Assistant Hydrovert</strong><span className="text-xs text-white/65">Réponses utiles, en quelques secondes</span></span></div><button type="button" onClick={() => setOpen(false)} aria-label="Fermer la bulle FAQ" className="rounded-full p-2 transition hover:bg-white/10"><X size={19}/></button></header>
      <div className="max-h-[min(65vh,520px)] overflow-y-auto p-4">
        {!selected ? <><p className="px-1 pb-3 text-sm leading-6 text-slate-600">Écrivez votre question ou choisissez un sujet fréquent.</p><form onSubmit={submit} className="flex gap-2"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Ex. combien arroser ?" className="min-w-0 flex-1 rounded-xl border border-[#cddbc4] bg-white px-3 py-2.5 text-sm outline-none ring-[#79b852] focus:ring-2"/><button aria-label="Rechercher" type="submit" className="grid size-10 place-items-center rounded-xl bg-[#315c2b] text-white"><Send size={17}/></button></form><div className="mt-3 space-y-2">{results.length ? results.map((answer) => <button type="button" key={answer.question} onClick={() => choose(answer)} className="w-full rounded-xl border border-[#dbe5d4] bg-white px-3 py-3 text-left text-sm font-medium leading-5 text-[#18241d] transition hover:border-[#79b852] hover:bg-[#eff7e9]">{answer.question}</button>) : <div className="rounded-xl bg-white p-4 text-sm leading-6 text-slate-600">Nous n&apos;avons pas trouvé de réponse exacte. Décrivez votre terrain afin que nous puissions vous orienter.</div>}</div></> : <div><button type="button" onClick={() => setSelected(null)} className="inline-flex items-center gap-1 text-sm font-semibold text-[#315c2b] hover:underline"><ChevronLeft size={16}/>Toutes les questions</button><p className="mt-5 text-lg font-semibold text-[#18241d]">{selected.question}</p><p className="mt-3 leading-7 text-slate-600">{selected.answer}</p>{selected.link && <Link href={selected.link.href} onClick={() => setOpen(false)} className="mt-5 inline-flex rounded-full bg-[#315c2b] px-4 py-2.5 text-sm font-bold text-white hover:bg-[#10271d]">{selected.link.label}</Link>}<p className="mt-5 border-t border-[#dbe5d4] pt-4 text-sm text-slate-500">Une question spécifique ? <Link href="/contact" onClick={() => setOpen(false)} className="font-semibold text-[#315c2b] hover:underline">Parlons de votre terrain.</Link></p></div>}
      </div>
    </section>}
    <button type="button" onClick={() => setOpen(!open)} aria-expanded={open} aria-label={open ? "Fermer l'assistant" : "Ouvrir l'assistant"} className="group flex items-center gap-3 rounded-full bg-[#10271d] py-3 pl-4 pr-5 text-left text-white shadow-xl shadow-black/25 transition hover:-translate-y-0.5 hover:bg-[#315c2b]"><span className="grid size-9 place-items-center rounded-full bg-[#c0ea93] text-[#10271d]"><MessageCircleMore size={20}/></span><span className="hidden sm:block"><strong className="block text-sm">Une question ?</strong><span className="block text-xs text-white/65">Assistant Hydrovert</span></span></button>
  </div>;
}
