"use client";

import Link from "next/link";
import { Bot, ChevronLeft, MessageCircleMore, Send, X } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";

type Answer = {
  question: string;
  answer: string;
  keywords: string[];
  link?: { href: string; label: string };
};

const answers: Answer[] = [
  { question: "Qu'est-ce que l'hydroseeding ?", answer: "C'est une projection hydraulique qui associe de l'eau, des semences et des fibres de paillage. Le mélange est choisi en fonction du terrain et de l'objectif du projet.", keywords: ["hydroseeding", "hydroseed", "hydrosemis", "technique", "definition"], link: { href: "/hydroseeding", label: "Découvrir l'hydroseeding" } },
  { question: "Qu'est-ce que l'hydromulching ?", answer: "L'hydromulching projette une couverture de fibres de paillage et de liant sur le sol. Elle aide à conserver l'humidité de surface et à limiter l'érosion superficielle. Des semences peuvent être ajoutées selon le projet.", keywords: ["hydromulching", "hydromulch", "paillage", "fibre"], link: { href: "/hydromulching", label: "Découvrir l'hydromulching" } },
  { question: "Quelle différence entre hydroseeding et hydromulching ?", answer: "L'hydroseeding vise principalement l'installation d'une végétation à partir de semences. L'hydromulching met l'accent sur la couverture et la protection du sol ; il peut être associé à des semences selon le besoin.", keywords: ["difference", "différence", "hydroseeding hydromulching", "choisir"], link: { href: "/hydromulching", label: "Comparer les deux approches" } },
  { question: "Quels terrains peuvent être traités ?", answer: "Talus, zones de chantier, grandes surfaces, espaces paysagers et sols nus à protéger peuvent être concernés. Nous regardons d'abord le sol, la pente, l'accès et le résultat recherché.", keywords: ["terrain", "surface", "talus", "pente", "chantier", "adapté", "application"], link: { href: "/applications", label: "Voir les applications" } },
  { question: "Faut-il préparer le terrain ?", answer: "Pas systématiquement. Nous évaluons le terrain et proposons seulement les interventions utiles. Une surface compacte, instable ou encombrée peut toutefois nécessiter une préparation avant la projection.", keywords: ["preparer", "préparer", "préparation", "sol", "compact", "nivellement" ] },
  { question: "Peut-on intervenir sur une pente ?", answer: "Oui, la pente fait partie des éléments étudiés. L'exposition au ruissellement, la stabilité du sol et l'accès permettent de définir si une projection seule suffit ou si une protection complémentaire est nécessaire.", keywords: ["pente", "talus", "incliné", "erosion", "érosion", "ruissellement"] },
  { question: "Comment choisissez-vous les semences ?", answer: "Le mélange n'est pas identique pour tous les projets. Il est choisi selon le sol, le climat local, l'exposition, l'usage du terrain et l'objectif de végétalisation.", keywords: ["semence", "graine", "mélange", "melange", "choisir", "espèce", "espece"] },
  { question: "Pourquoi arroser après un hydroseeding ?", answer: "Les premières semaines, l'eau aide à conserver un environnement favorable à la germination. Le paillage doit rester humide au toucher, sans être détrempé ni créer de ruissellement.", keywords: ["arroser", "arrosage", "irrigation", "eau", "humide", "apres", "après"], link: { href: "/guide-irrigation", label: "Voir le guide 30 jours" } },
  { question: "Combien de fois arroser les premiers jours ?", answer: "En repère général, comptez 2 à 4 passages courts par jour pendant les jours 1 à 7. La météo, le vent, la pente, le débit et le sol imposent d'ajuster : observez toujours l'humidité du paillage.", keywords: ["combien", "fois", "jour", "jours", "premier", "fréquence", "frequence", "2", "4"], link: { href: "/guide-irrigation", label: "Voir le calendrier complet" } },
  { question: "Combien de temps faut-il arroser ?", answer: "Il n'existe pas de durée universelle : elle dépend du débit de l'arroseur, du sol, de la pente et de la météo. Comme simple repère, un sol lourd peut parfois demander 5 à 15 minutes par passage. Arrêtez dès que la surface brille, forme des flaques ou commence à ruisseler.", keywords: ["minute", "minutes", "temps", "duree", "durée", "longtemps", "programmateur"] },
  { question: "Que faire s'il fait très chaud ou s'il y a du vent ?", answer: "Contrôlez davantage le paillage. S'il sèche vite, ajoutez un passage court et doux plutôt que d'arroser fortement en une seule fois.", keywords: ["chaud", "chaleur", "canicule", "vent", "sec", "secher", "sécher"] },
  { question: "Dois-je arroser quand il pleut ?", answer: "Vérifiez d'abord le terrain. Une pluie légère ne remplace pas toujours l'irrigation ; si le paillage reste humide, il n'est pas nécessaire d'ajouter de l'eau immédiatement.", keywords: ["pluie", "pleut", "pluvieux", "orage"] },
  { question: "Quand les premières pousses apparaissent-elles ?", answer: "Dans de bonnes conditions, certaines graminées peuvent lever en 5 à 10 jours, tandis que les espèces plus lentes peuvent demander 2 à 3 semaines, parfois davantage. Une levée progressive est donc normale : gardez l'ensemble de la zone humide jusqu'à la germination des variétés les plus lentes.", keywords: ["pousse", "germination", "germer", "délai", "delai", "quand", "apparaitre", "apparaître", "lever", "levée"] },
  { question: "Pourquoi certaines zones poussent moins bien ?", answer: "Les écarts peuvent venir de la météo, de l'ombre, de la pente, de l'humidité, de la nature du sol ou d'un ruissellement localisé. Une observation du terrain permet d'identifier la bonne action.", keywords: ["zone", "moins", "trou", "clairsemé", "clairseme", "inégal", "inegal", "pousse pas"] },
  { question: "Que faire si l'eau ruisselle ?", answer: "Réduisez l'intensité du jet ou divisez l'arrosage en passages plus courts. L'objectif est d'humidifier le paillage sans déplacer le mélange ni former de flaques.", keywords: ["ruissellement", "flaque", "flaques", "coule", "ecoulement", "écoulement"] },
  { question: "Quand tondre un nouveau gazon ?", answer: "Tondez quand l'herbe dépasse d'environ un tiers la hauteur que vous souhaitez conserver et quand le terrain supporte vos pas sans coucher durablement les jeunes pousses. Utilisez une tondeuse légère, une lame bien affûtée et ne retirez jamais plus d'un tiers de la hauteur en une fois.", keywords: ["tondre", "tonte", "couper", "gazon", "première coupe", "premiere coupe", "hauteur"] },
  { question: "Est-ce que cela protège contre l'érosion ?", answer: "Une couverture de paillage peut limiter l'érosion superficielle pendant l'installation de la végétation. Sur un sol instable ou une pente très exposée, une étude plus complète peut être nécessaire.", keywords: ["erosion", "érosion", "protéger", "protection", "stabiliser", "stabilité"] },
  { question: "À quelle saison intervenir ?", answer: "On recherche une période où la température favorise la germination et où l'eau peut être apportée régulièrement. Les fenêtres les plus favorables varient selon la région et les espèces ; une période fraîche et humide est souvent plus simple qu'une forte chaleur, un gel ou une sécheresse.", keywords: ["saison", "printemps", "été", "ete", "automne", "hiver", "periode", "période", "meilleur moment"] },
  { question: "Est-ce adapté aux grandes surfaces ?", answer: "Oui, l'application hydraulique peut être intéressante sur de grandes surfaces. L'accès, la topographie et le résultat attendu sont étudiés avant de définir la solution.", keywords: ["grande", "grandes", "surface", "hectare", "m2", "m²"] },
  { question: "Peut-on hydrosemer un petit jardin ?", answer: "Oui, selon la configuration et l'objectif. La surface seule ne suffit pas à décider : l'accès, l'état du sol et le résultat recherché sont aussi importants.", keywords: ["petit", "jardin", "particulier", "maison", "pelouse"] },
  { question: "Peut-on intervenir dans un espace public ?", answer: "Oui, les espaces publics, accotements et zones paysagères peuvent être étudiés. Les contraintes d'accès, de fréquentation et de sécurité doivent être intégrées au projet.", keywords: ["public", "collectivite", "collectivité", "commune", "mairie", "voirie", "accotement"] },
  { question: "L'accès au terrain est-il important ?", answer: "Oui. L'accès influence l'organisation du chantier, le positionnement du matériel et la manière d'atteindre la zone à traiter. Des photos et les dimensions des accès nous aident à préparer l'intervention.", keywords: ["acces", "accès", "portail", "passage", "difficile", "machine", "matériel"] },
  { question: "Que faut-il retirer avant l'intervention ?", answer: "Les déchets, pierres mobiles, objets et végétaux indésirables peuvent devoir être retirés. Nous vous indiquons ce qui est réellement nécessaire après avoir regardé le terrain.", keywords: ["retirer", "nettoyer", "pierre", "dechet", "déchet", "mauvaise herbe", "désherber"] },
  { question: "Peut-on projeter sur une pelouse existante ?", answer: "Cela dépend de l'état de la pelouse et de l'objectif. Une végétation dense peut empêcher les semences d'atteindre correctement le sol ; une préparation peut donc être utile.", keywords: ["pelouse existante", "ancien gazon", "regarnir", "gazon actuel", "déjà", "deja"] },
  { question: "Est-ce adapté à un sol argileux ?", answer: "Un sol argileux peut être concerné, mais sa compaction, son drainage et sa capacité à retenir l'eau doivent être observés. Le mélange et la préparation éventuelle sont ajustés en conséquence.", keywords: ["argile", "argileux", "lourd", "collant", "sol lourd"] },
  { question: "Est-ce adapté à un sol sableux ?", answer: "Un sol sableux sèche généralement plus vite et retient moins l'eau. Le choix du mélange et le suivi d'arrosage doivent donc être adaptés à ce comportement.", keywords: ["sable", "sableux", "drainant", "sec"] },
  { question: "Et si le terrain est très caillouteux ?", answer: "Un terrain très caillouteux doit être observé avant de choisir la méthode. Les pierres, le manque de terre fine et la stabilité de la surface peuvent nécessiter une préparation complémentaire.", keywords: ["caillou", "caillouteux", "pierre", "roche", "rocheux"] },
  { question: "Faut-il analyser le sol ?", answer: "Une observation du sol est toujours utile. Selon le projet, une analyse plus poussée peut aider à comprendre le pH, la fertilité ou certaines contraintes avant de choisir les composants.", keywords: ["analyse", "ph", "fertilite", "fertilité", "terre", "tester"] },
  { question: "Le drainage du terrain est-il important ?", answer: "Oui. Une eau qui stagne ou ruisselle fortement peut perturber l'installation de la végétation. Le drainage et les écoulements doivent être pris en compte avant l'intervention.", keywords: ["drainage", "drainer", "stagne", "eau stagnante", "boue", "inondé"] },
  { question: "Faut-il un système d'arrosage automatique ?", answer: "Ce n'est pas toujours obligatoire, mais il facilite un arrosage régulier, surtout sur une grande surface. L'essentiel est de pouvoir humidifier toute la zone de façon douce et homogène.", keywords: ["automatique", "arroseur", "programmateur", "systeme", "système", "irrigation automatique"] },
  { question: "Que faire si je n'ai pas d'arrivée d'eau ?", answer: "Il faut anticiper une solution avant l'intervention. Les premiers jours demandent une humidité régulière ; sans moyen d'arrosage adapté, la réussite peut être fortement compromise.", keywords: ["pas eau", "sans eau", "arrivee", "arrivée", "robinet", "citerne"] },
  { question: "Puis-je marcher sur la zone après l'intervention ?", answer: "Évitez autant que possible les passages jusqu'à ce que le gazon soit bien enraciné et ait supporté plusieurs tontes. Au début, le piétinement peut déplacer le paillage, compacter le sol, coucher ou arracher les jeunes pousses.", keywords: ["marcher", "passer", "piétiner", "pietiner", "circuler", "passage", "trafic"] },
  { question: "Les enfants ou animaux peuvent-ils aller sur la zone ?", answer: "Il est préférable de protéger temporairement la zone du passage. Demandez-nous aussi les consignes adaptées aux composants utilisés sur votre chantier.", keywords: ["chien", "chat", "animal", "animaux", "enfant", "enfants", "sécurité", "securite"] },
  { question: "Pourquoi le mélange projeté est-il coloré ?", answer: "Une coloration peut servir de repère visuel pendant l'application afin de mieux contrôler la couverture de la surface. Son aspect évolue ensuite avec le séchage et la météo.", keywords: ["vert", "bleu", "couleur", "coloré", "colore", "teinte"] },
  { question: "Le paillage va-t-il disparaître ?", answer: "Les fibres évoluent progressivement avec l'humidité, la météo et l'installation de la végétation. Leur aspect visible diminue au fil du temps.", keywords: ["paillage", "disparaitre", "disparaître", "fibre", "reste", "partir"] },
  { question: "Que faire après un gros orage ?", answer: "Observez la zone sans la piétiner : cherchez d'éventuels écoulements, déplacements de paillage ou zones dénudées. Envoyez-nous des photos si quelque chose vous semble anormal.", keywords: ["orage", "tempete", "tempête", "forte pluie", "dégât", "degat"] },
  { question: "Le gel peut-il gêner la germination ?", answer: "Oui, les températures basses peuvent ralentir ou interrompre temporairement la germination. La période d'intervention doit tenir compte des semences et des conditions locales.", keywords: ["gel", "geler", "froid", "gelée", "gelee", "hiver"] },
  { question: "L'ombre change-t-elle le résultat ?", answer: "Oui. Une zone ombragée reçoit moins de lumière et conserve parfois l'humidité différemment. Le choix des semences et le rythme d'arrosage doivent en tenir compte.", keywords: ["ombre", "ombragé", "ombrage", "soleil", "lumiere", "lumière"] },
  { question: "Les mauvaises herbes peuvent-elles apparaître ?", answer: "Oui. L'arrosage peut aussi faire germer des graines déjà présentes dans le sol. Évitez de traiter immédiatement un jeune gazon : beaucoup de désherbants peuvent l'endommager. Identifiez d'abord les plantes et attendez que le gazon soit suffisamment établi, en respectant strictement l'étiquette du produit.", keywords: ["mauvaise herbe", "adventice", "herbe indésirable", "indesirable", "désherber", "desherbant", "désherbant", "herbicide"] },
  { question: "Faut-il ajouter de l'engrais après la projection ?", answer: "Pas automatiquement. Le mélange peut déjà contenir un fertilisant de démarrage. Un apport supplémentaire se décide selon le sol, la croissance et ce qui a déjà été appliqué ; une analyse de sol est la meilleure base pour éviter un excès ou un apport inutile.", keywords: ["engrais", "fertilisant", "fertiliser", "amendement", "nourrir", "azote", "phosphore"] },
  { question: "Que faire après les 30 premiers jours ?", answer: "Lorsque la végétation est installée, les arrosages deviennent généralement plus espacés et plus profonds. La tonte, la fertilisation et l'entretien dépendent ensuite du mélange et de l'usage du terrain.", keywords: ["apres 30", "après 30", "un mois", "entretien", "ensuite", "suite"] },
  { question: "Que faire si une zone reste clairsemée ?", answer: "Ne corrigez pas trop vite. Comparez l'humidité, l'exposition et le sol avec le reste du terrain, puis envoyez-nous des photos pour déterminer s'il faut attendre ou intervenir.", keywords: ["clairsemé", "clairseme", "trou", "vide", "reprendre", "ressemer"] },
  { question: "Le résultat est-il garanti ?", answer: "La germination dépend aussi de l'arrosage, de la météo, du sol et du suivi après l'intervention. Nous préférons expliquer clairement ces facteurs et vous accompagner plutôt que promettre un résultat indépendant des conditions.", keywords: ["garantie", "garantir", "assuré", "assure", "réussite", "reussite"] },
  { question: "Combien de temps dure une intervention ?", answer: "La durée dépend de la surface, de l'accès, de la pente et des préparations nécessaires. Nous pouvons donner un repère après avoir compris le terrain.", keywords: ["durée chantier", "duree chantier", "temps intervention", "combien temps", "journée", "journee"] },
  { question: "Quelles photos envoyer pour étudier le projet ?", answer: "Envoyez une vue générale, plusieurs angles du terrain, les pentes, les accès et les zones présentant une difficulté particulière. Une photo prise avec du recul est souvent très utile.", keywords: ["photo", "photos", "image", "envoyer", "angle", "vue"] },
  { question: "Comment savoir quelle solution choisir ?", answer: "Vous n'avez pas besoin de choisir seul. Décrivez le terrain et votre objectif ; nous vous expliquons si l'hydroseeding, l'hydromulching ou une autre préparation paraît la plus cohérente.", keywords: ["quelle solution", "choisir", "conseil", "besoin", "méthode", "methode"] },
  { question: "Quels sont les signes d'un manque d'eau ?", answer: "Le paillage s'éclaircit et devient sec au toucher, puis les jeunes pousses peuvent perdre leur tenue ou leur couleur. Intervenez avant un dessèchement complet avec un passage doux, sans chercher à compenser par une inondation.", keywords: ["manque eau", "pas assez", "sous arrosage", "sec", "dessèchement", "dessechement", "fané", "fane"] },
  { question: "Quels sont les signes d'un excès d'eau ?", answer: "Des flaques persistantes, un sol spongieux, du ruissellement ou des plantules molles et couchées signalent un excès possible. Réduisez la durée ou la fréquence et laissez l'eau s'infiltrer entre les cycles.", keywords: ["trop eau", "excès", "exces", "sur arrosage", "détrempé", "detrempe", "spongieux", "flaque"] },
  { question: "À quel moment de la journée arroser ?", answer: "Le matin est généralement le créneau le plus efficace. Pendant la germination, plusieurs passages courts peuvent néanmoins être nécessaires dans la journée pour empêcher la surface de sécher. Évitez surtout les arrosages longs qui maintiennent la zone saturée toute la nuit.", keywords: ["heure", "matin", "soir", "midi", "nuit", "moment", "quand arroser"] },
  { question: "Comment vérifier que l'arrosage couvre toute la surface ?", answer: "Placez plusieurs récipients identiques dans la zone pendant un cycle et comparez les niveaux d'eau. Des écarts importants révèlent un mauvais chevauchement, un obstacle, du vent ou un arroseur mal réglé.", keywords: ["uniforme", "couverture", "arroseur", "récipient", "recipient", "boite", "boîte", "chevauchement"] },
  { question: "Quel type de jet utiliser ?", answer: "Utilisez une pluie fine et douce qui humidifie sans frapper le sol. Un jet concentré peut creuser la surface, déplacer les fibres et rassembler les semences.", keywords: ["jet", "lance", "pistolet", "buse", "pression", "doux", "pluie fine"] },
  { question: "Comment arroser une pente sans ruissellement ?", answer: "Fractionnez l'arrosage en cycles courts séparés par un temps d'infiltration. Cette méthode permet au sol d'absorber l'eau avant le passage suivant et limite le déplacement du mélange vers le bas de la pente.", keywords: ["cycle", "fractionner", "pente", "ruissellement", "infiltration", "pause"] },
  { question: "La pluie juste après la projection est-elle dangereuse ?", answer: "Une pluie douce peut être favorable. Une pluie intense peut provoquer du ruissellement ou déplacer le mélange, surtout sur une pente. Après un gros épisode, observez la surface à distance et envoyez-nous des photos des zones dénudées ou accumulées.", keywords: ["pluie après", "juste après", "averse", "forte pluie", "orage", "déplacé", "deplace"] },
  { question: "Pourquoi le paillage se fissure-t-il en séchant ?", answer: "Un léger changement d'aspect peut accompagner le séchage. Si les fissures sont larges, si la surface se soulève ou si le sol apparaît très sec, contrôlez l'humidité et contactez-nous avec des photos avant d'intervenir.", keywords: ["fissure", "craque", "craquelé", "craquele", "se soulève", "souleve"] },
  { question: "Une pellicule blanche ou des filaments apparaissent : que faire ?", answer: "Une zone blanchâtre, visqueuse ou des plantules qui s'effondrent peuvent être liées à une humidité excessive ou à une maladie de jeunes semis. Réduisez la saturation, évitez les arrosages prolongés et envoyez rapidement des photos pour identification.", keywords: ["blanc", "moisissure", "champignon", "filament", "visqueux", "maladie", "pourriture"] },
  { question: "Les oiseaux peuvent-ils manger les graines ?", answer: "Une partie des graines peut attirer les oiseaux, mais le paillage aide à les dissimuler et à les maintenir en place. Évitez de poser des objets ou filets directement sur les jeunes pousses sans vérifier qu'ils sont adaptés.", keywords: ["oiseau", "oiseaux", "manger", "graines", "pigeon"] },
  { question: "Faut-il enlever les feuilles mortes ?", answer: "Oui si elles forment une couche qui prive les jeunes pousses de lumière. Retirez-les délicatement avec un souffleur réglé au minimum ou à la main, sans ratisser agressivement ni arracher les plantules.", keywords: ["feuille", "feuilles", "automne", "ramasser", "souffleur", "râteau", "rateau"] },
  { question: "Que faire des déchets de première tonte ?", answer: "Des résidus fins et bien répartis peuvent rester. S'ils forment des paquets humides qui couvrent le jeune gazon, ramassez-les délicatement afin de ne pas étouffer les pousses.", keywords: ["déchet tonte", "dechet tonte", "herbe coupée", "herbe coupee", "ramasser", "clippings"] },
  { question: "Peut-on utiliser un robot tondeuse rapidement ?", answer: "Attendez que le gazon soit bien enraciné, que le sol soit ferme et que plusieurs tontes classiques aient confirmé sa résistance. Les passages répétés et les roues d'un robot peuvent marquer un jeune terrain encore fragile.", keywords: ["robot", "tondeuse robot", "automower", "roue"] },
  { question: "Quand peut-on utiliser un désherbant ?", answer: "Un jeune gazon est sensible. De nombreux désherbants ne doivent pas être appliqués avant plusieurs semaines ou plusieurs tontes. Identifiez la mauvaise herbe, lisez l'étiquette et demandez conseil avant tout traitement.", keywords: ["désherbant", "desherbant", "herbicide", "traiter", "pulvériser", "pulveriser", "mauvaises herbes"] },
  { question: "Peut-on semer à nouveau les zones manquantes ?", answer: "Oui, mais seulement après avoir compris la cause : manque d'eau, ruissellement, ombre, sol compacté ou germination plus lente. Une reprise trop précoce risque de perturber des graines qui n'ont pas encore levé.", keywords: ["ressemer", "regarnir", "reprendre", "zone nue", "manque", "réparation", "reparation"] },
  { question: "Pourquoi la pousse est-elle plus rapide près des arroseurs ?", answer: "Cela indique souvent une répartition d'eau inégale. Vérifiez le chevauchement des jets et comparez les quantités reçues avec plusieurs petits récipients placés dans chaque zone.", keywords: ["près arroseur", "pres arroseur", "plus vite", "inégal", "inegal", "différence", "difference"] },
  { question: "La pente peut-elle rester partiellement visible ?", answer: "Oui pendant l'installation : les espèces ne germent pas toutes au même rythme et certaines zones sèchent plus vite. Surveillez surtout l'absence de ravines, de déplacements du mélange et de zones durablement sèches.", keywords: ["pente visible", "terre visible", "pas couvert", "partiellement", "ravine"] },
  { question: "L'hydroseeding corrige-t-il un sol compacté ?", answer: "Non. L'hydroseeding est un traitement de surface ; il ne décompacte pas le sol, ne corrige pas un mauvais drainage et ne restaure pas à lui seul la structure ou les réserves nutritives. Une préparation peut être nécessaire.", keywords: ["compacté", "compacte", "structure", "mauvais sol", "corriger sol", "décompacter", "decompacter"] },
  { question: "L'hydromulching suffit-il sur toutes les fortes pentes ?", answer: "Non. Lorsque le risque de ruissellement ou d'instabilité est élevé, un filet, une natte ou un autre dispositif de contrôle de l'érosion peut être nécessaire en complément. La pente doit être étudiée avant de choisir.", keywords: ["forte pente", "filet", "natte", "instable", "hydromulching suffit", "érosion forte"] },
  { question: "Le paillage remplace-t-il la terre végétale ?", answer: "Non. Le paillage protège la surface et aide à conserver l'humidité ; il ne remplace pas un sol offrant une profondeur, une structure et une fertilité suffisantes pour les racines.", keywords: ["terre végétale", "terre vegetale", "topsoil", "remplace terre", "épaisseur terre", "epaisseur terre"] },
  { question: "Pourquoi faire une analyse de sol avant le chantier ?", answer: "Elle peut révéler un pH inadapté ou des carences et guider les apports de chaux, de phosphore, de potassium ou d'autres amendements. Elle évite de fertiliser au hasard.", keywords: ["analyse sol", "test sol", "carence", "chaux", "potassium", "phosphore", "pH"] },
  { question: "Peut-on arroser avec une eau très calcaire ou salée ?", answer: "La qualité de l'eau peut influencer le sol et les jeunes plantes. En cas d'eau très salée, recyclée ou inhabituelle, signalez-le avant le chantier afin d'évaluer sa compatibilité.", keywords: ["calcaire", "salée", "salee", "qualité eau", "qualite eau", "forage", "puits", "eau recyclée"] },
  { question: "Que faire si le terrain reste boueux plusieurs jours ?", answer: "Suspendez les arrosages automatiques et vérifiez le drainage. Un sol durablement saturé manque d'air et peut fragiliser les plantules. Photographiez les zones concernées et contactez-nous.", keywords: ["boue", "boueux", "saturé", "sature", "plusieurs jours", "stagne"] },
  { question: "Quand le gazon peut-il être utilisé normalement ?", answer: "Attendez qu'il soit bien enraciné et qu'il ait supporté plusieurs tontes. La date varie selon les espèces, la saison et le terrain ; une pelouse encore tendre ou qui garde les traces de pas n'est pas prête pour un usage normal.", keywords: ["utiliser", "jouer", "usage", "normalement", "résistant", "resistant", "combien semaines"] },
  { question: "Comment reconnaître un gazon bien enraciné ?", answer: "Les pousses se redressent après un passage léger, résistent à une traction très douce et le sol supporte une tondeuse légère sans marquer. Évitez toutefois de multiplier les tests sur une zone jeune.", keywords: ["enraciné", "enracine", "racine", "bien installé", "resiste", "résiste"] },
  { question: "Dois-je modifier l'arrosage après la première tonte ?", answer: "Oui, si le gazon est homogène et bien enraciné, commencez progressivement à espacer les arrosages tout en humidifiant plus profondément. Évitez un changement brutal qui laisserait sécher les jeunes racines.", keywords: ["après tonte", "apres tonte", "modifier arrosage", "espacer", "racines profondes"] },
  { question: "Est-ce que vos équipes réalisent les chantiers ?", answer: "Oui. Hydrovert Solutions réalise directement ses interventions. Vous échangez avec une équipe impliquée dans votre projet, sans multiplication d'intermédiaires.", keywords: ["équipe", "equipe", "sous traitance", "sous-traitance", "intermediaire", "intermédiaire", "realisez", "réalisez"] },
  { question: "Quel accompagnement proposez-vous ?", answer: "Nous échangeons avant l'intervention pour comprendre le terrain et l'objectif, puis restons disponibles pour les conseils utiles après la projection, notamment sur l'arrosage.", keywords: ["accompagnement", "suivi", "conseil", "apres", "après", "disponible"] },
  { question: "Comment demander un devis ?", answer: "Indiquez la localisation, la surface approximative, la pente ou les contraintes, votre objectif et, si possible, quelques photos. Ces éléments permettent de démarrer un échange utile.", keywords: ["devis", "demande", "projet", "contacter"], link: { href: "/devis", label: "Préparer une demande" } },
  { question: "Intervenez-vous partout en France ?", answer: "Le site présente Hydrovert Solutions comme intervenant en France. Pour confirmer la faisabilité et les conditions de votre zone, transmettez-nous la localisation de votre terrain.", keywords: ["france", "ville", "departement", "département", "zone", "distance", "intervenir"] },
];

const popular = [answers[0], answers[7], answers[2], answers.find((item) => item.question === "Comment demander un devis ?")!];

function normalize(value: string) {
  return value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");
}

export default function FaqBubble() {
  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState<Answer | null>(null);

  const results = useMemo(() => {
    const words = normalize(query).split(/\s+/).filter((word) => word.length > 2);
    if (!words.length) return popular;
    return answers
      .map((item) => {
        const normalizedQuestion = normalize(item.question);
        const normalizedKeywords = item.keywords.map(normalize);
        const score = words.reduce((total, word) => {
          const questionMatch = normalizedQuestion.includes(word) ? 3 : 0;
          const keywordMatch = normalizedKeywords.some((keyword) => keyword.includes(word) || word.includes(keyword)) ? 2 : 0;
          return total + questionMatch + keywordMatch;
        }, 0);
        return { item, score };
      })
      .filter(({ score }) => score > 0)
      .sort((a, b) => b.score - a.score)
      .slice(0, 6)
      .map(({ item }) => item);
  }, [query]);

  function choose(answer: Answer) { setSelected(answer); setQuery(""); }
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (results[0]) choose(results[0]); }

  return <div className="fixed bottom-4 right-4 z-[60] sm:bottom-6 sm:right-6">
    {open && <section aria-label="Assistant Hydrovert" className="mb-3 w-[calc(100vw-2rem)] max-w-md overflow-hidden rounded-3xl border border-[#dbe5d4] bg-[#f7f8f4] shadow-2xl shadow-black/20">
      <header className="flex items-center justify-between bg-[#10271d] px-5 py-4 text-white"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-full bg-[#c0ea93] text-[#10271d]"><Bot size={20}/></span><span><strong className="block text-sm">Assistant Hydrovert</strong><span className="text-xs text-white/65">Réponses utiles, en quelques secondes</span></span></div><button type="button" onClick={() => setOpen(false)} aria-label="Fermer la bulle FAQ" className="rounded-full p-2 transition hover:bg-white/10"><X size={19}/></button></header>
      <div className="max-h-[min(72vh,620px)] overflow-y-auto p-4">
        {!selected ? <><p className="px-1 pb-3 text-sm leading-6 text-slate-600">Posez une question pratique sur l&apos;hydroseeding ou choisissez un sujet fréquent.</p><form onSubmit={submit} className="flex gap-2"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Ex. mon paillage devient sec…" className="min-w-0 flex-1 rounded-xl border border-[#cddbc4] bg-white px-3 py-2.5 text-sm outline-none ring-[#79b852] focus:ring-2"/><button aria-label="Rechercher" type="submit" className="grid size-10 place-items-center rounded-xl bg-[#315c2b] text-white"><Send size={17}/></button></form><div className="mt-3 space-y-2">{results.length ? results.map((answer) => <button type="button" key={answer.question} onClick={() => choose(answer)} className="w-full rounded-xl border border-[#dbe5d4] bg-white px-3 py-3 text-left text-sm font-medium leading-5 text-[#18241d] transition hover:border-[#79b852] hover:bg-[#eff7e9]">{answer.question}</button>) : <div className="rounded-xl bg-white p-4 text-sm leading-6 text-slate-600">Nous n&apos;avons pas trouvé de réponse suffisamment précise. Envoyez-nous votre question et, si possible, une photo du terrain.</div>}</div></> : <div><button type="button" onClick={() => setSelected(null)} className="inline-flex items-center gap-1 text-sm font-semibold text-[#315c2b] hover:underline"><ChevronLeft size={16}/>Toutes les questions</button><p className="mt-5 text-lg font-semibold text-[#18241d]">{selected.question}</p><p className="mt-3 leading-7 text-slate-600">{selected.answer}</p>{selected.link && <Link href={selected.link.href} onClick={() => setOpen(false)} className="mt-5 inline-flex rounded-full bg-[#315c2b] px-4 py-2.5 text-sm font-bold text-white hover:bg-[#10271d]">{selected.link.label}</Link>}<p className="mt-5 border-t border-[#dbe5d4] pt-4 text-sm text-slate-500">Les conditions réelles du chantier restent prioritaires. <Link href="/contact" onClick={() => setOpen(false)} className="font-semibold text-[#315c2b] hover:underline">Nous poser une question précise.</Link></p></div>}
      </div>
    </section>}
    <button type="button" onClick={() => setOpen(!open)} aria-expanded={open} aria-label={open ? "Fermer l'assistant" : "Ouvrir l'assistant"} className="group flex items-center gap-3 rounded-full bg-[#10271d] py-3 pl-4 pr-5 text-left text-white shadow-xl shadow-black/25 transition hover:-translate-y-0.5 hover:bg-[#315c2b]"><span className="grid size-9 place-items-center rounded-full bg-[#c0ea93] text-[#10271d]"><MessageCircleMore size={20}/></span><span className="hidden sm:block"><strong className="block text-sm">Une question ?</strong><span className="block text-xs text-white/65">Assistant Hydrovert</span></span></button>
  </div>;
}
