import Link from "next/link";
import { ArrowLeft, Check, CloudRain, Droplets, Sun, Wind } from "lucide-react";

export const metadata = {
  title: "Guide d'irrigation après hydroseeding | Hydrovert Solutions",
  description: "Un guide pratique sur les 30 premiers jours après un hydroseeding : fréquence, observation du paillage et adaptations selon la météo.",
};

const phases = [
  { period: "Jours 1 à 7", frequency: "2 à 4 passages / jour", title: "Garder le paillage uniformément humide", text: "L'objectif est d'humidifier la surface sans la détremper. Par temps chaud, sec ou venteux, plusieurs irrigations courtes réparties dans la journée peuvent être nécessaires.", note: "Repère de durée : sur un sol lourd, 5 à 15 minutes par zone peuvent parfois suffire. Vérifiez toujours l'humidité réelle : le débit, la pente et le sol changent tout." },
  { period: "Jours 8 à 14", frequency: "1 à 3 passages / jour", title: "Accompagner la germination", text: "Les premières pousses peuvent apparaître selon les semences et la météo. Gardez le premier centimètre de sol humide ; réduisez seulement si l'humidité reste présente entre deux passages.", note: "Ne cherchez pas une fréquence fixe : l'état du paillage est le meilleur indicateur." },
  { period: "Jours 15 à 21", frequency: "En général 1 passage / jour", title: "Commencer à espacer", text: "Lorsque les jeunes pousses sont bien présentes, espacez progressivement les irrigations. L'eau peut pénétrer un peu plus en profondeur, sans laisser le terrain sécher brutalement.", note: "Une irrigation trop forte peut créer du ruissellement et déplacer le paillage." },
  { period: "Jours 22 à 30", frequency: "Tous les 2 à 3 jours, à ajuster", title: "Encourager l'enracinement", text: "Si la végétation s'installe, privilégiez des irrigations plus espacées et un peu plus profondes. Le but est d'encourager les racines à aller chercher l'eau plus bas.", note: "Après 30 jours, le rythme dépend encore de la saison, du sol, des espèces semées et de la météo." },
];

export default function GuideIrrigationPage() {
  return (
    <main className="min-h-screen bg-[#f7f8f4] text-[#18241d]">
      <section className="bg-[#10271d] px-6 pb-20 pt-32 text-white sm:px-8 lg:px-12 lg:pt-40">
        <div className="mx-auto max-w-7xl"><Link href="/" className="inline-flex items-center gap-2 text-sm font-semibold text-[#c9efa6] hover:text-white"><ArrowLeft size={17}/>Retour à l&apos;accueil</Link><p className="mt-12 text-xs font-bold uppercase tracking-[.25em] text-[#c9efa6]">Guide d&apos;irrigation · 30 jours</p><h1 className="mt-5 max-w-5xl text-4xl font-semibold tracking-[-.05em] sm:text-5xl lg:text-7xl">Après l&apos;hydroseeding, l&apos;irrigation fait la différence.</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-white/75 sm:text-xl">Ce guide donne des repères généraux. Le bon rythme dépend toujours du sol, de l&apos;exposition, du vent, de la pluie et du débit de votre installation d&apos;irrigation.</p></div>
      </section>

      <section className="mx-auto max-w-7xl px-6 py-16 sm:px-8 lg:px-12 lg:py-24"><div className="mb-10 max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.24em] text-[#4f7e31]">Le réflexe à garder</p><h2 className="mt-4 text-3xl font-semibold tracking-[-.04em] sm:text-4xl">Humide au toucher. Jamais saturé.</h2><p className="mt-5 text-lg leading-8 text-slate-600">Touchez le paillage : il doit rester humide, sans flaques et sans eau qui s&apos;écoule. C&apos;est plus fiable qu&apos;un nombre de minutes identique pour tous les terrains.</p></div><div className="grid gap-px overflow-hidden rounded-3xl border border-[#dbe5d4] bg-[#dbe5d4] md:grid-cols-2">{phases.map((phase) => <article key={phase.period} className="bg-white p-7 sm:p-9"><p className="text-sm font-bold uppercase tracking-[.18em] text-[#79a65d]">{phase.period}</p><p className="mt-6 text-3xl font-semibold tracking-[-.04em] text-[#315c2b]">{phase.frequency}</p><h3 className="mt-7 text-2xl font-semibold">{phase.title}</h3><p className="mt-4 leading-7 text-slate-600">{phase.text}</p><p className="mt-5 border-l-2 border-[#a9cf91] pl-4 text-sm leading-6 text-slate-600">{phase.note}</p></article>)}</div></section>

      <section className="border-y border-[#dbe5d4] bg-white"><div className="mx-auto grid max-w-7xl divide-y divide-[#dbe5d4] px-6 sm:px-8 md:grid-cols-3 md:divide-x md:divide-y-0 lg:px-12"><article className="py-9 md:px-8 md:first:pl-0"><Sun className="text-[#4f7e31]" size={28}/><h2 className="mt-4 text-xl font-semibold">Chaleur ou vent</h2><p className="mt-3 leading-7 text-slate-600">Contrôlez plus souvent. Si le paillage sèche rapidement, ajoutez une irrigation courte plutôt qu&apos;une irrigation trop intense.</p></article><article className="py-9 md:px-8"><CloudRain className="text-[#4f7e31]" size={28}/><h2 className="mt-4 text-xl font-semibold">Pluie</h2><p className="mt-3 leading-7 text-slate-600">Ne reprenez pas l&apos;irrigation automatiquement : vérifiez si le sol reste humide. Une pluie légère ne remplace pas toujours l&apos;irrigation.</p></article><article className="py-9 md:px-8 md:pr-0"><Wind className="text-[#4f7e31]" size={28}/><h2 className="mt-4 text-xl font-semibold">Pente</h2><p className="mt-3 leading-7 text-slate-600">Utilisez un jet doux. Si de l&apos;eau ruisselle, réduisez l&apos;intensité ou divisez l&apos;irrigation en passages plus courts.</p></article></div></section>

      <section className="mx-auto max-w-7xl px-6 py-16 sm:px-8 lg:px-12 lg:py-24"><div className="grid gap-8 rounded-3xl bg-[#eaf2e5] p-7 sm:p-10 lg:grid-cols-[.9fr_1.1fr]"><div><Droplets className="text-[#4f7e31]" size={32}/><h2 className="mt-5 text-3xl font-semibold">Les erreurs à éviter</h2></div><ul className="grid gap-4 sm:grid-cols-2">{["Laisser le paillage devenir clair et sec", "Créer des flaques ou du ruissellement", "Utiliser un jet qui déplace le mélange", "Suivre un minuteur sans regarder le terrain"].map((item) => <li key={item} className="flex gap-3 rounded-2xl bg-white p-4 leading-6 text-slate-700"><Check className="mt-0.5 shrink-0 text-[#4f7e31]" size={18}/>{item}</li>)}</ul></div><p className="mx-auto mt-14 max-w-3xl text-center leading-8 text-slate-600">Un hydroseeding soigné a besoin d&apos;un suivi cohérent pour laisser les semences s&apos;installer. Ces repères ne remplacent pas les recommandations adaptées à votre mélange et à votre terrain : en cas de doute, contactez-nous avant de modifier fortement votre irrigation.</p></section>
    </main>
  );
}
